// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8PEOTJGLthu1q_dPTgRD1_ZAiKHJXs6s',
    appId: '1:101062720901:web:1aa6b6a772dba2795f18ec',
    messagingSenderId: '101062720901',
    projectId: 'sharemate-c882d',
    authDomain: 'sharemate-c882d.firebaseapp.com',
    storageBucket: 'sharemate-c882d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7mhJ2wy2RWN_MRleTv84hPxj447zmZJQ',
    appId: '1:101062720901:android:754183e26d3369255f18ec',
    messagingSenderId: '101062720901',
    projectId: 'sharemate-c882d',
    storageBucket: 'sharemate-c882d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqLdXFH14cXWu4vK-Gmxcz3d1JJh2Se7Q',
    appId: '1:101062720901:ios:772886a2bf302a085f18ec',
    messagingSenderId: '101062720901',
    projectId: 'sharemate-c882d',
    storageBucket: 'sharemate-c882d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqLdXFH14cXWu4vK-Gmxcz3d1JJh2Se7Q',
    appId: '1:101062720901:ios:772886a2bf302a085f18ec',
    messagingSenderId: '101062720901',
    projectId: 'sharemate-c882d',
    storageBucket: 'sharemate-c882d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8PEOTJGLthu1q_dPTgRD1_ZAiKHJXs6s',
    appId: '1:101062720901:web:5ab59c089c6500895f18ec',
    messagingSenderId: '101062720901',
    projectId: 'sharemate-c882d',
    authDomain: 'sharemate-c882d.firebaseapp.com',
    storageBucket: 'sharemate-c882d.firebasestorage.app',
  );

}